unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a
set -g mouse on

#use vim based keybinds
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Open new windows and splits in the same directory as the current pane
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
### theme settings ###

# window separators
set-option -wg window-status-separator ""

# monitor window changes
set-option -wg monitor-activity on
set-option -wg monitor-bell on

# set statusbar update interval
set-option -g status-interval 1


# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"


# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Configure the catppuccin plugin
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"
set -g @catppuccin_window_current_text " #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

# Configure the status bar
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right ""
# Ensure that everything on the right side of the status line is included.
set -g status-right-length 100



# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g status-position top 

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Pane border styling for better visibility (After TPM to prevent override)
set -g pane-border-style "fg=#414559" # Dim Frappe surface color for inactive
set -g pane-active-border-style "fg=#ca9ee6" # Bright Frappe Mauve for active
